### ISSUE TITLE
Change licence to MIT?

### ISSUE THREAD

**Issue by soyuka** [random-access-storage/random-access-http#19]
@e-e-e @bcomnes  may I?

Also do you guys have the rights to publish on npm?

**Comment by e-e-e** [comment]
@soyuka yeah I will do this asap. Its an oversight that its not MIT already. Thanks for picking it up.

**Comment by e-e-e** [comment]
Oh actually I dont know if it was an oversight or not. I completely forgot that this is not the lib that I wrote but a merge with @bcomnes version. @bcomnes do you mind if we change the license?

**Comment by e-e-e** [comment]
@soyuka I just published the fixes that you did patched recently. Sorry for the delay.

**Comment by soyuka** [comment]
Don't worry about delays it's open source and I have all the time in the world :). Also we can still use the git version if it's not published :).

**Comment by bcomnes** [comment]
This is done.
